name: Test & Build

on: [push]

jobs:
  test:
    env:
      MQTT_HOST: ${{ secrets.MQTT_HOST }}
      MQTT_USER: ${{ secrets.MQTT_USER }}
      MQTT_PASS: ${{ secrets.MQTT_PASS }}
      NATS_URL: ${{ secrets.NATS_URL }}
      NATS_TOKEN: ${{ secrets.NATS_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: touch packages/better-mqtt/.env
      - run: touch packages/rpc/.env
      - run: touch packages/postgres-schema-tools/.env
      - run: pnpm -r run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build